services:
  db:
    image: mariadb:11
    container_name: etude-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etude
    ports:
      - "3306:3306"
    volumes:
      - etude-db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  etude-db-data:
