-- 세트 1: 리눅스 기초 1 — 파일 탐색과 생성 (order 1~10)
INSERT INTO quest (quest_set_id, order_index, title, description, hint, solution, setup_cmd, grade_cmd) VALUES
  (1,  1, '현재 위치 확인하기',
   '현재 작업 중인 디렉토리의 경로를 /tmp/pwd_result.txt 에 저장하세요.',
   'pwd 명령어와 리다이렉션(>)을 사용하세요.',
   'pwd > /tmp/pwd_result.txt',
   NULL,
   '["sh", "-c", "grep -q / /tmp/pwd_result.txt"]'),

  (1,  2, '디렉토리 이동하기',
   '/tmp 디렉토리로 이동한 뒤, 현재 위치를 /tmp/pwd_result.txt 에 저장하세요.',
   'cd로 이동 후 pwd > /tmp/pwd_result.txt 로 저장하세요.',
   'cd /tmp && pwd > /tmp/pwd_result.txt',
   NULL,
   '["sh", "-c", "grep -q /tmp /tmp/pwd_result.txt"]'),

  (1,  3, '파일 목록 확인하기',
   '/etc 디렉토리의 파일 목록을 /tmp/ls_result.txt 에 저장하세요.',
   'ls 명령어와 리다이렉션(>)을 사용하세요.',
   'ls /etc > /tmp/ls_result.txt',
   NULL,
   '["sh", "-c", "grep -q passwd /tmp/ls_result.txt"]'),

  (1,  4, '파일 상세 목록 확인하기',
   '/etc 디렉토리의 파일 목록을 숨김 파일 포함 상세하게 /tmp/ls_detail.txt 에 저장하세요.',
   'ls -al 명령어를 사용하세요. -a는 숨김 파일 포함, -l은 상세 출력입니다.',
   'ls -al /etc > /tmp/ls_detail.txt',
   NULL,
   '["sh", "-c", "grep -q ^total /tmp/ls_detail.txt"]'),

  (1,  5, '디렉토리 만들기',
   '/tmp 경로 안에 hello라는 이름의 디렉토리를 만드세요.',
   'mkdir 명령어를 사용하세요.',
   'mkdir /tmp/hello',
   NULL,
   '["test", "-d", "/tmp/hello"]'),

  (1,  6, '빈 파일 만들기',
   '/tmp/empty.txt 라는 이름의 빈 파일을 만드세요.',
   'touch 명령어를 사용하세요.',
   'touch /tmp/empty.txt',
   NULL,
   '["test", "-f", "/tmp/empty.txt"]'),

  (1,  7, '파일에 내용 쓰기',
   '/tmp/answer.txt 파일을 만들고 첫 줄에 "done"을 입력하세요.',
   'echo 명령어와 리다이렉션(>)을 사용하세요.',
   'echo "done" > /tmp/answer.txt',
   NULL,
   '["grep", "-q", "done", "/tmp/answer.txt"]'),

  (1,  8, '숨김 파일 만들기',
   '/tmp 경로에 .hidden 이라는 이름의 빈 파일을 만드세요.',
   'touch 명령어를 사용하세요. 파일명 앞에 .을 붙이면 숨김 파일이 됩니다.',
   'touch /tmp/.hidden',
   NULL,
   '["test", "-f", "/tmp/.hidden"]'),

  (1,  9, '파일 복사하기',
   '/tmp/answer.txt 파일을 /tmp/backup.txt 로 복사하세요.',
   'cp 명령어를 사용하세요.',
   'cp /tmp/answer.txt /tmp/backup.txt',
   '["sh", "-c", "echo done > /tmp/answer.txt"]',
   '["test", "-f", "/tmp/backup.txt"]'),

  (1, 10, '파일 이름 바꾸기',
   '/tmp/backup.txt 파일의 이름을 /tmp/renamed.txt 로 변경하세요.',
   'mv 명령어는 파일 이동뿐 아니라 이름 변경에도 사용됩니다.',
   'mv /tmp/backup.txt /tmp/renamed.txt',
   '["sh", "-c", "echo done > /tmp/backup.txt"]',
   '["test", "-f", "/tmp/renamed.txt"]');
