-- 세트 10: 리눅스 현장 운영 (order 1~12)
INSERT INTO quest (quest_set_id, order_index, title, description, hint, solution, setup_cmd, grade_cmd) VALUES
  (10,  1, 'systemd 서비스 상태 확인하기',
   'cron 서비스의 상태를 확인하고 결과를 /tmp/svc_status.txt 에 저장하세요.',
   'systemctl status <서비스명> 명령어를 사용하세요.',
   'systemctl status cron > /tmp/svc_status.txt 2>&1',
   '["sh", "-c", "apt-get install -y cron > /dev/null 2>&1"]',
   '["sh", "-c", "grep -qi ''cron'' /tmp/svc_status.txt"]'),

  (10,  2, 'systemd 서비스 시작하고 활성화하기',
   'cron 서비스를 시작하고 부팅 시 자동 시작되도록 활성화하세요.',
   'systemctl start 와 systemctl enable 을 사용하세요.',
   'systemctl start cron && systemctl enable cron',
   '["sh", "-c", "apt-get install -y cron > /dev/null 2>&1 && systemctl stop cron 2>/dev/null || true"]',
   '["sh", "-c", "systemctl is-active cron"]'),

  (10,  3, '환경변수 설정하기 (/etc/profile.d)',
   '/etc/profile.d/myapp.sh 파일을 만들어 APP_HOME=/opt/myapp 환경변수를 등록하세요.',
   'export APP_HOME=/opt/myapp 을 파일에 작성하면 됩니다.',
   'echo "export APP_HOME=/opt/myapp" > /etc/profile.d/myapp.sh',
   NULL,
   '["sh", "-c", "grep -q ''APP_HOME=/opt/myapp'' /etc/profile.d/myapp.sh"]'),

  (10,  4, '시스템 계정 생성하기',
   '서비스용 시스템 계정 "myservice" 를 생성하세요. 로그인 셸 없이 시스템 계정으로 만들어야 합니다.',
   'useradd -r -s /sbin/nologin <계정명> 을 사용하세요.',
   'useradd -r -s /sbin/nologin myservice',
   NULL,
   '["sh", "-c", "id myservice"]'),

  (10,  5, '/etc/hosts 에 호스트 등록하기',
   '/etc/hosts 에 "192.168.1.100 db.internal" 항목을 추가하세요.',
   'echo 로 /etc/hosts 에 추가하거나 vim으로 편집하세요.',
   'echo "192.168.1.100 db.internal" >> /etc/hosts',
   NULL,
   '["sh", "-c", "grep -q ''192.168.1.100 db.internal'' /etc/hosts"]'),

  (10,  6, '포트 사용 현황 확인하기',
   '현재 리스닝 중인 TCP 포트 목록을 /tmp/ports.txt 에 저장하세요.',
   'ss -tlnp 또는 netstat -tlnp 를 사용하세요.',
   'ss -tlnp > /tmp/ports.txt',
   NULL,
   '["sh", "-c", "grep -qi ''listen\\|LISTEN'' /tmp/ports.txt"]'),

  (10,  7, 'tar로 디렉토리 백업하기',
   '/etc 디렉토리를 /tmp/etc_backup.tar.gz 로 압축 백업하세요.',
   'tar -czf <출력파일> <대상디렉토리> 를 사용하세요.',
   'tar -czf /tmp/etc_backup.tar.gz /etc 2>/dev/null || true',
   NULL,
   '["sh", "-c", "test -f /tmp/etc_backup.tar.gz"]'),

  (10,  8, '바이너리 실행 파일 PATH 등록하기',
   '/opt/mytool/bin 디렉토리를 만들고 PATH에 추가되도록 /etc/profile.d/mytool.sh 를 작성하세요.',
   'export PATH=$PATH:/opt/mytool/bin 을 profile.d 파일에 작성하세요.',
   'mkdir -p /opt/mytool/bin && echo "export PATH=\$PATH:/opt/mytool/bin" > /etc/profile.d/mytool.sh',
   NULL,
   '["sh", "-c", "grep -q ''/opt/mytool/bin'' /etc/profile.d/mytool.sh"]'),

  (10,  9, '스크립트에 실행 권한 주기 (chmod +x)',
   '/opt/myapp/start.sh 파일에 실행 권한을 부여하세요.',
   'chmod +x <파일경로> 를 사용하세요.',
   'chmod +x /opt/myapp/start.sh',
   '["sh", "-c", "mkdir -p /opt/myapp && echo ''#!/bin/bash'' > /opt/myapp/start.sh"]',
   '["sh", "-c", "[ -x /opt/myapp/start.sh ]"]'),

  (10, 10, '디렉토리 소유권 변경하기 (chown)',
   'myservice 계정을 생성하고 /opt/myapp 디렉토리의 소유자를 myservice 로 변경하세요.',
   'useradd -r -s /sbin/nologin myservice 후 chown -R myservice:myservice /opt/myapp 을 사용하세요.',
   'useradd -r -s /sbin/nologin myservice 2>/dev/null || true && chown -R myservice:myservice /opt/myapp',
   '["sh", "-c", "mkdir -p /opt/myapp"]',
   '["sh", "-c", "[ $(stat -c %U /opt/myapp) = myservice ]"]'),

  (10, 11, '실행 파일 권한 755로 설정하기',
   '/opt/myapp/start.sh 파일 권한을 755 로 설정하세요. 소유자는 읽기/쓰기/실행, 그룹과 기타는 읽기/실행만 허용합니다.',
   'chmod 755 <파일경로> 를 사용하세요.',
   'chmod 755 /opt/myapp/start.sh',
   '["sh", "-c", "mkdir -p /opt/myapp && echo ''#!/bin/bash'' > /opt/myapp/start.sh && chmod 600 /opt/myapp/start.sh"]',
   '["sh", "-c", "[ $(stat -c %a /opt/myapp/start.sh) = 755 ]"]'),

  (10, 12, '설정 파일 권한 제한하기 (chmod 600)',
   '/etc/myapp/secret.conf 에 비밀번호가 담긴 설정 파일이 있습니다. 소유자만 읽고 쓸 수 있도록 권한을 600 으로 변경하세요.',
   'chmod 600 <파일경로> 를 사용하세요. 600 은 소유자만 읽기/쓰기 가능입니다.',
   'chmod 600 /etc/myapp/secret.conf',
   '["sh", "-c", "mkdir -p /etc/myapp && echo ''password=secret'' > /etc/myapp/secret.conf"]',
   '["sh", "-c", "[ $(stat -c %a /etc/myapp/secret.conf) = 600 ]"]');
