-- 세트 9: Vim 기초 (order 1~12)
INSERT INTO quest (quest_set_id, order_index, title, description, hint, solution, setup_cmd, grade_cmd) VALUES
  (9,  1, 'Vim으로 파일 열고 저장하기',
   '/tmp/hello.txt 파일을 vim으로 열어 첫 줄에 "hello vim" 을 입력하고 저장 후 종료하세요.',
   'i 키로 입력 모드 진입 → 텍스트 입력 → ESC → :wq',
   'vim /tmp/hello.txt 후 i → hello vim → ESC → :wq',
   NULL,
   '["sh", "-c", "grep -q ''hello vim'' /tmp/hello.txt"]'),

  (9,  2, '저장 없이 Vim 종료하기',
   '/tmp/test.txt 를 vim으로 열어 아무 내용이나 입력한 뒤, 저장하지 않고 종료하세요. 그 다음 파일이 비어있는지 확인하세요.',
   'ESC → :q! 로 저장 없이 강제 종료합니다.',
   'vim /tmp/test.txt 후 i → 내용 입력 → ESC → :q!',
   '["sh", "-c", "touch /tmp/test.txt"]',
   '["sh", "-c", "! grep -q . /tmp/test.txt"]'),

  (9,  3, '특정 줄 번호로 이동하기',
   '/tmp/lines.txt 파일의 5번째 줄 내용을 /tmp/result.txt 에 저장하세요. vim에서 줄 번호로 이동한 뒤 해당 줄을 확인하세요.',
   'vim에서 :5 를 입력하면 5번째 줄로 이동합니다. sed -n ''5p'' 로도 확인할 수 있습니다.',
   'sed -n ''5p'' /tmp/lines.txt > /tmp/result.txt',
   '["sh", "-c", "printf ''line1\\nline2\\nline3\\nline4\\nline5\\nline6\\n'' > /tmp/lines.txt"]',
   '["sh", "-c", "grep -q ''line5'' /tmp/result.txt"]'),

  (9,  4, '단어 검색하기',
   '/tmp/config.txt 에서 "port" 라는 단어를 vim으로 검색하고, 검색된 줄 번호를 /tmp/result.txt 에 저장하세요.',
   'vim에서 /port 로 검색합니다. grep -n 으로도 줄 번호를 확인할 수 있습니다.',
   'grep -n "port" /tmp/config.txt > /tmp/result.txt',
   '["sh", "-c", "printf ''host=localhost\\nport=8080\\nuser=admin\\n'' > /tmp/config.txt"]',
   '["sh", "-c", "grep -q ''2'' /tmp/result.txt"]'),

  (9,  5, '줄 삭제하기 (dd)',
   '/tmp/remove.txt 의 2번째 줄을 vim에서 dd 명령으로 삭제하고 저장하세요.',
   'vim에서 :2 로 이동 후 dd 로 줄을 삭제합니다.',
   'vim /tmp/remove.txt 후 :2 → dd → :wq',
   '["sh", "-c", "printf ''keep\\ndelete_me\\nkeep2\\n'' > /tmp/remove.txt"]',
   '["sh", "-c", "! grep -q ''delete_me'' /tmp/remove.txt"]'),

  (9,  6, '줄 복사 붙여넣기 (yy, p)',
   '/tmp/copy.txt 의 1번째 줄을 복사해서 파일 끝에 붙여넣고 저장하세요. 파일은 총 3줄이 되어야 합니다.',
   'vim에서 gg 로 첫 줄 이동 → yy 로 복사 → G 로 끝으로 이동 → p 로 붙여넣기',
   'vim /tmp/copy.txt 후 gg → yy → G → p → :wq',
   '["sh", "-c", "printf ''hello\\nworld\\n'' > /tmp/copy.txt"]',
   '["sh", "-c", "[ $(wc -l < /tmp/copy.txt) -ge 3 ]"]'),

  (9,  7, '단어 치환하기 (:%s)',
   '/tmp/app.conf 에서 "localhost" 를 "192.168.1.10" 으로 전체 치환하고 저장하세요.',
   'vim에서 :%s/localhost/192.168.1.10/g 를 실행합니다.',
   'vim /tmp/app.conf 후 :%s/localhost/192.168.1.10/g → :wq',
   '["sh", "-c", "printf ''host=localhost\\nbackup=localhost\\n'' > /tmp/app.conf"]',
   '["sh", "-c", "grep -q ''192.168.1.10'' /tmp/app.conf && ! grep -q ''localhost'' /tmp/app.conf"]'),

  (9,  8, '비주얼 모드로 여러 줄 삭제하기',
   '/tmp/multi.txt 에서 2~4번째 줄을 vim 비주얼 모드(V)로 선택해 삭제하고 저장하세요.',
   'vim에서 :2 이동 → V 로 비주얼 라인 모드 → j j 로 선택 확장 → d 로 삭제',
   'vim /tmp/multi.txt 후 :2 → V → jj → d → :wq',
   '["sh", "-c", "printf ''line1\\nline2\\nline3\\nline4\\nline5\\n'' > /tmp/multi.txt"]',
   '["sh", "-c", "[ $(wc -l < /tmp/multi.txt) -eq 2 ]"]'),

  (9,  9, '단어 교체하기 (cw)',
   '/tmp/fix.txt 의 첫 줄에서 "error" 단어를 vim에서 cw 로 "info" 로 바꾸고 저장하세요.',
   'vim에서 /error 로 검색 후 커서를 단어 위에 두고 cw 입력 → info 입력 → ESC → :wq',
   'vim /tmp/fix.txt 후 /error → cw → info → ESC → :wq',
   '["sh", "-c", "printf ''level: error\\n'' > /tmp/fix.txt"]',
   '["sh", "-c", "grep -q ''info'' /tmp/fix.txt && ! grep -q ''error'' /tmp/fix.txt"]'),

  (9, 10, '줄 끝에 내용 추가하기 (A)',
   '/tmp/append.txt 의 첫 줄 끝에 " # managed by etude" 를 추가하고 저장하세요.',
   'vim에서 첫 줄로 이동 후 A 키를 누르면 줄 끝 입력 모드로 진입합니다.',
   'vim /tmp/append.txt 후 gg → A → " # managed by etude" → ESC → :wq',
   '["sh", "-c", "printf ''server_name localhost;\\n'' > /tmp/append.txt"]',
   '["sh", "-c", "grep -q ''managed by etude'' /tmp/append.txt"]'),

  (9, 11, '실행 취소와 다시 실행 (u, Ctrl+r)',
   '/tmp/undo.txt 를 vim으로 열어 내용을 수정했다가 u 로 되돌리고 저장하세요. 파일 내용이 원본과 같아야 합니다.',
   'vim에서 수정 후 ESC → u 로 실행 취소합니다.',
   'vim /tmp/undo.txt 후 수정 → ESC → u → :wq',
   '["sh", "-c", "printf ''original content\\n'' > /tmp/undo.txt"]',
   '["sh", "-c", "grep -q ''original content'' /tmp/undo.txt"]'),

  (9, 12, '읽기 전용 파일 수정 저장하기',
   '/tmp/readonly.txt 는 root 소유의 읽기 전용 파일입니다. vim으로 열어 "modified" 한 줄을 추가하고 :w !sudo tee % 로 저장하세요.',
   'vim에서 일반 :w 가 안 될 때 :w !sudo tee % 로 저장할 수 있습니다.',
   'vim /tmp/readonly.txt 후 G → o → modified → ESC → :w !sudo tee %',
   '["sh", "-c", "echo readonly_content > /tmp/readonly.txt && chmod 444 /tmp/readonly.txt"]',
   '["sh", "-c", "grep -q ''modified'' /tmp/readonly.txt"]');
