-- 세트 2: 리눅스 기초 2 — 삭제·검색·권한 (order 1~10)
INSERT INTO quest (quest_set_id, order_index, title, description, hint, solution, setup_cmd, grade_cmd) VALUES
  (2,  1, '파일 삭제하기',
   '/tmp/renamed.txt 파일을 삭제하세요.',
   'rm 명령어를 사용하세요.',
   'rm /tmp/renamed.txt',
   '["touch", "/tmp/renamed.txt"]',
   '["sh", "-c", "test ! -f /tmp/renamed.txt"]'),

  (2,  2, '디렉토리 삭제하기',
   '/tmp/hello 디렉토리를 삭제하세요.',
   'rm -r 옵션을 사용하면 디렉토리를 삭제할 수 있습니다.',
   'rm -r /tmp/hello',
   '["mkdir", "/tmp/hello"]',
   '["sh", "-c", "test ! -d /tmp/hello"]'),

  (2,  3, '파일 내용 출력하기',
   '/tmp/answer.txt 파일의 내용을 /tmp/cat_result.txt 에 저장하세요.',
   'cat 명령어와 리다이렉션(>)을 사용하세요.',
   'cat /tmp/answer.txt > /tmp/cat_result.txt',
   '["sh", "-c", "echo done > /tmp/answer.txt"]',
   '["sh", "-c", "grep -q done /tmp/cat_result.txt"]'),

  (2,  4, '파일에서 문자열 검색하기',
   '/tmp/answer.txt 파일에서 "done" 문자열이 포함된 줄을 출력하세요.',
   'grep 명령어를 사용하세요.',
   'grep "done" /tmp/answer.txt',
   '["sh", "-c", "echo done > /tmp/answer.txt"]',
   '["grep", "-q", "done", "/tmp/answer.txt"]'),

  (2,  5, '여러 줄 파일 만들기',
   '/tmp/multiline.txt 파일을 만들고 첫 줄에 "line1", 둘째 줄에 "line2"를 입력하세요.',
   'printf 명령어를 사용하세요. printf "line1\nline2\n" > /tmp/multiline.txt',
   'printf "line1\nline2\n" > /tmp/multiline.txt',
   NULL,
   '["grep", "-q", "line2", "/tmp/multiline.txt"]'),

  (2,  6, '파일 실행 권한 부여하기',
   '/tmp/answer.txt 파일에 실행 권한을 추가하세요.',
   'chmod 명령어를 사용하세요. +x 옵션으로 실행 권한을 추가할 수 있습니다.',
   'chmod +x /tmp/answer.txt',
   '["sh", "-c", "echo done > /tmp/answer.txt"]',
   '["sh", "-c", "test -x /tmp/answer.txt"]'),

  (2,  7, '심볼릭 링크 만들기',
   '/tmp/answer.txt 를 가리키는 심볼릭 링크 /tmp/link.txt 를 만드세요.',
   'ln -s 명령어를 사용하세요.',
   'ln -s /tmp/answer.txt /tmp/link.txt',
   '["sh", "-c", "echo done > /tmp/answer.txt"]',
   '["sh", "-c", "test -L /tmp/link.txt"]'),

  (2,  8, '중첩 디렉토리 만들기',
   '/tmp/a/b/c 경로를 한 번에 만드세요.',
   'mkdir -p 옵션을 사용하면 중간 디렉토리를 한 번에 만들 수 있습니다.',
   'mkdir -p /tmp/a/b/c',
   NULL,
   '["test", "-d", "/tmp/a/b/c"]'),

  (2,  9, '파일 찾기',
   '/tmp 경로에서 .txt 확장자를 가진 파일을 모두 찾아 /tmp/find_result.txt 에 저장하세요.',
   'find 명령어와 리다이렉션(>)을 사용하세요. find /tmp -name "*.txt"',
   'find /tmp -name "*.txt" > /tmp/find_result.txt',
   '["sh", "-c", "echo done > /tmp/answer.txt"]',
   '["sh", "-c", "grep -q .txt /tmp/find_result.txt"]'),

  (2, 10, '디스크 사용량 확인하기',
   '/tmp 디렉토리의 전체 사용량을 /tmp/du_result.txt 에 저장하세요.',
   'du -sh 명령어와 리다이렉션(>)을 사용하세요.',
   'du -sh /tmp > /tmp/du_result.txt',
   NULL,
   '["sh", "-c", "grep -q /tmp /tmp/du_result.txt"]');
