-- 세트 5: Docker 기초 (order 1~13)
INSERT INTO quest (quest_set_id, order_index, title, description, hint, solution, setup_cmd, grade_cmd) VALUES
  (5,  1, '로컬 이미지 목록 확인하기',
   'Docker에 저장된 이미지 목록을 확인하고, 결과를 /tmp/images.txt 에 저장하세요.',
   'docker images 명령어를 사용하세요.',
   'docker images > /tmp/images.txt',
   '["sh", "-c", "docker pull hello-world"]',
   '["sh", "-c", "grep -q hello-world /tmp/images.txt"]'),

  (5,  2, '이미지 받아오기',
   'Docker Hub에서 hello-world 이미지를 받아오세요.',
   'docker pull 명령어를 사용하세요.',
   'docker pull hello-world',
   NULL,
   '["sh", "-c", "docker images hello-world | grep -q hello-world"]'),

  (5,  3, '컨테이너 실행하기',
   'hello-world 이미지로 컨테이너를 실행하세요.',
   'docker run 명령어를 사용하세요.',
   'docker run hello-world',
   NULL,
   '["sh", "-c", "docker ps -a | grep -q hello-world"]'),

  (5,  4, '백그라운드 컨테이너 실행하기',
   'nginx 이미지를 백그라운드로 실행하고 이름을 my-nginx 로 지정하세요.',
   'docker run -d --name 옵션을 사용하세요.',
   'docker run -d --name my-nginx nginx',
   NULL,
   '["sh", "-c", "docker ps | grep -q my-nginx"]'),

  (5,  5, '실행 중인 컨테이너 목록 저장하기',
   '현재 실행 중인 컨테이너 목록을 /tmp/containers.txt 에 저장하세요.',
   'docker ps 명령어를 사용하세요.',
   'docker ps > /tmp/containers.txt',
   '["sh", "-c", "docker run -d --name my-nginx nginx"]',
   '["test", "-s", "/tmp/containers.txt"]'),

  (5,  6, '컨테이너 로그 확인하기',
   'my-nginx 컨테이너의 로그를 확인하고 결과를 /tmp/nginx_logs.txt 에 저장하세요.',
   'docker logs 명령어를 사용하세요.',
   'docker logs my-nginx > /tmp/nginx_logs.txt 2>&1',
   '["sh", "-c", "docker run -d --name my-nginx nginx"]',
   '["test", "-f", "/tmp/nginx_logs.txt"]'),

  (5,  7, '컨테이너 중지하기',
   'my-nginx 컨테이너를 중지하세요.',
   'docker stop 명령어를 사용하세요.',
   'docker stop my-nginx',
   '["sh", "-c", "docker run -d --name my-nginx nginx"]',
   '["sh", "-c", "docker ps | grep -qv my-nginx"]'),

  (5,  8, '컨테이너 삭제하고 결과 저장하기',
   'my-nginx 컨테이너를 삭제한 뒤, 전체 컨테이너 목록(중지 포함)을 /tmp/final.txt 에 저장하세요.',
   'docker rm으로 삭제 후 docker ps -a > /tmp/final.txt 로 저장하세요.',
   'docker rm my-nginx
docker ps -a > /tmp/final.txt',
   '["sh", "-c", "docker run -d --name my-nginx nginx && docker stop my-nginx"]',
   '["sh", "-c", "test -s /tmp/final.txt && ! grep -q my-nginx /tmp/final.txt"]'),

  (5,  9, '실행 중인 컨테이너 안으로 들어가기',
   'my-nginx 컨테이너 안에서 bash 셸을 실행하고, /usr/share/nginx/html/index.html 파일이 존재하는지 확인한 뒤 /tmp/exec_result.txt 에 저장하세요.',
   'docker exec -it <컨테이너명> bash 로 컨테이너 안으로 들어갈 수 있습니다. 컨테이너 밖에서 docker exec <컨테이너명> <명령어> 로도 실행 가능합니다.',
   'docker exec my-nginx ls /usr/share/nginx/html/index.html > /tmp/exec_result.txt',
   '["sh", "-c", "docker run -d --name my-nginx nginx"]',
   '["sh", "-c", "grep -q ''index.html'' /tmp/exec_result.txt"]'),

  (5, 10, '포트 바인딩으로 컨테이너 실행하기',
   'nginx 컨테이너를 호스트 8080 포트와 컨테이너 80 포트를 연결해서 실행하세요. 컨테이너 이름은 port-nginx 로 지정하세요.',
   'docker run -p <호스트포트>:<컨테이너포트> 형식을 사용하세요.',
   'docker run -d -p 8080:80 --name port-nginx nginx',
   NULL,
   '["sh", "-c", "docker ps | grep port-nginx | grep -q ''0.0.0.0:8080''"]'),

  (5, 11, '환경변수 주입해서 컨테이너 실행하기',
   'ubuntu 컨테이너를 MY_ENV=hello 환경변수를 주입해서 실행하고, 컨테이너 안에서 해당 변수를 출력한 결과를 /tmp/env_result.txt 에 저장하세요.',
   'docker run -e <변수명>=<값> 으로 환경변수를 주입합니다. docker exec로 컨테이너 안에서 printenv 를 실행할 수 있습니다.',
   'docker run -d --name env-test -e MY_ENV=hello ubuntu sleep 60 && docker exec env-test printenv MY_ENV > /tmp/env_result.txt',
   NULL,
   '["sh", "-c", "grep -q ''hello'' /tmp/env_result.txt"]'),

  (5, 12, '볼륨 마운트해서 컨테이너 실행하기',
   '/tmp/webroot 디렉토리를 만들고 index.html 을 생성한 뒤, nginx 컨테이너의 /usr/share/nginx/html 에 마운트해서 실행하세요.',
   'docker run -v <호스트경로>:<컨테이너경로> 형식으로 마운트합니다.',
   'mkdir -p /tmp/webroot && echo "hello" > /tmp/webroot/index.html && docker run -d -v /tmp/webroot:/usr/share/nginx/html --name vol-nginx nginx',
   NULL,
   '["sh", "-c", "docker ps | grep -q vol-nginx && docker exec vol-nginx cat /usr/share/nginx/html/index.html | grep -q hello"]'),

  (5, 13, '컨테이너 상세 정보 확인하기',
   'my-nginx 컨테이너의 상세 정보를 확인하고 IP 주소를 /tmp/inspect.txt 에 저장하세요.',
   'docker inspect <컨테이너명> 으로 상세 정보를 확인할 수 있습니다. grep IPAddress 로 IP만 추출할 수 있어요.',
   'docker run -d --name my-nginx nginx && docker inspect my-nginx | grep IPAddress > /tmp/inspect.txt',
   NULL,
   '["sh", "-c", "grep -q ''IPAddress'' /tmp/inspect.txt"]');
