# Etude API 테스트
# REST Client 확장 설치 후 각 요청 위에 뜨는 "Send Request" 클릭

@baseUrl = http://localhost:3001

### 서버 헬스 체크
GET {{baseUrl}}/

### (Phase 2에서 추가될 예정)
### 퀘스트 목록 조회
# GET {{baseUrl}}/quests

### 채점 요청
# POST {{baseUrl}}/grade
# Content-Type: application/json
#
# {
#   "containerId": "abc123",
#   "questId": "q1"
# }
